--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/PortableCrafting
build-by-default: true
branches:
- master
projects:
  PortableCrafting:
    path: ""
    icon: poggit/icon.png
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.7.4
...
