name: PortableCrafting
main: muqsit\portablecrafting\PortableCrafting
api: 4.0.0
version: 0.0.1
permissions:
  portablecrafting.command.workbench:
    default: op
commands:
  workbench:
    permission: portablecrafting.command.workbench