name: PortableCrafting
main: muqsit\portablecrafting\PortableCrafting
api: 4.0.0
version: 0.1.0
permissions:
  portablecrafting.command.workbench:
    default: true
commands:
  workbench:
    permission: portablecrafting.command.workbench