name: PortableCrafting
main: muqsit\portablecrafting\PortableCrafting
api: 4.0.0
version: 0.1.1
permissions:
  portablecrafting.command.workbench:
    default: true
    description: Permits executing /workbench command
commands:
  workbench:
    permission: portablecrafting.command.workbench
    description: Opens a portable crafting table window